name: romankasevich
favicon: null
layout_spectrum: 0.77284
typography_spectrum: 0.82498
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#717171'
    - '#a1a1a1'
    - '#dadada'
    - '#b71c2a'
  brandStrength: 0.75
  lightness: 0
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
