name: romankasevich
favicon: null
layout_spectrum: 0.2070524082519114
typography_spectrum: 0.1971245282329619
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.005034129833802581
  lightness: 0.5673846320714802
  saturation: 0.9134975527413189
  rhythmicContrast: 0.24856005841866136
purpose: []
