name: blog.romankasevich
favicon: null
layout_spectrum: 0.88582
typography_spectrum: 0.82498
title: Блог Романа Касевича
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#717171'
    - '#a1a1a1'
    - '#dadada'
    - '#b71c2a'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
