name: romankasevich
favicon: null
layout_spectrum: 1
typography_spectrum: 0.68915
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eeeef0'
    - '#d72731'
    - '#a2aaac'
    - '#e37e8c'
    - '#221012'
  brandStrength: 0.5625
  lightness: 0.125
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
