name: romankasevich
favicon: null
layout_spectrum: 1
typography_spectrum: 0.82498
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f9fc'
    - '#151517'
    - '#ca1a1d'
    - '#535355'
    - '#fe88a1'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
